<a href="https://colab.research.google.com/github/gizattos/Python/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>Importando NumPy e criando um array</h2>


In [1]:
import numpy as np

a = np.array([[1,2,2],[2,2,2]])
a 

array([[1, 2, 2],
       [2, 2, 2]])

<h2>Verificando número de dimensões</h2>




In [36]:
a.ndim

2

In [30]:
np.zeros((40,50,50,50)).ndim

4

<h2>Mostrando quantidade de linhas e colunas</h2>

In [32]:
a.shape

(2, 3)

In [33]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b.shape

(3, 5)

<h2>Mostrando quantidade de informações presentes no array</h2>

In [34]:
a.size

6

In [35]:
b.size

15

<h2>Operações com array</h2>

In [19]:
a+1


array([[2, 3, 3],
       [3, 3, 3]])

In [20]:
a**2

array([[1, 4, 4],
       [4, 4, 4]])

In [21]:
a-10

array([[-9, -8, -8],
       [-8, -8, -8]])

In [22]:
(a*3) >5

array([[False,  True,  True],
       [ True,  True,  True]])

In [23]:
a+b

ValueError: ignored

In [28]:
c = np.array([[2,1,1],[1,1,1]])
a+c

array([[3, 3, 3],
       [3, 3, 3]])

In [42]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[5,5,5,5,5,5],[5,5,5,5,5,5],[5,5,5,5,5,5]])
## A quantidade de colunas do primeiro deve ser igual a quantidade de linhas do segundo
array1@array2


array([[ 30,  30,  30,  30,  30,  30],
       [ 75,  75,  75,  75,  75,  75],
       [120, 120, 120, 120, 120, 120]])

In [43]:
## Invertendo
array2@array1

ValueError: ignored

<h2>Indexing & Slicing</h2>

In [44]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a[1][2]

6

In [46]:
## Retornando todas as linhas exceto a segunda
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
## retornando linhas a cada duas posições
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [48]:
a[2][3]

11

In [49]:
a[2:,2]

array([10])

In [50]:
a[2][2]

10

In [52]:
a[2,2:]

array([10, 11])

In [53]:
a[2:]

array([[ 8,  9, 10, 11]])

In [54]:
## Invertendo ordem 
a[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [55]:
## trazendo valores maiores que 5
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

<h2>Stacking (juntando arrays)</h2>

In [56]:
np.vstack((a,b))

ValueError: ignored

In [57]:
## deixando array b com a mesma quantidade de colunas e juntando com a
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

<h2>Funções Estatísticas</h2>

In [59]:
a = np.arange(24).reshape(8,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [60]:

a.mean()

11.5

In [61]:
a.var()

47.916666666666664

In [63]:
a.std()

6.922186552431729

In [64]:
np.median(a)

11.5

In [65]:
## Primeiro Quartil
np.quantile(a,0.25)

5.75